[theme]
name = "bad-wolf"
[theme.overrides]

[icons]
name = "none"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp58s0"
ssid = true
ip = true
bitrate = false
speed_up = false
graph_up = false
speed_down = false
graph_down = false
interval = 5

[[block]]
block = "disk_space"
path = "/home/francis"
alias = "HOME"
info_type = "available"
unit = "GB"
interval = 600
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/"
alias = "ROOT"
info_type = "available"
unit = "GB"
interval = 600
warning = 10.0
alert = 5.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
interval = 30

[[block]]
block = "load"
interval = 300
format = "{5m} {15m}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %H:%M"

